name: weather_wardrobe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  file_picker: ^8.0.0
  http: ^1.2.0
  flutter_stripe: ^12.1.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/logo.png" 
  min_sdk_android: 21 # Optional, but good for modern Android
  adaptive_icon_background: "#ffffff" # Optional: Background color for Android adaptive icons
  adaptive_icon_foreground: "lib/assets/icon/logo.png" # Optional: Foreground image for adaptive icons